# Site settings
title: Software
email: bitard [dot] michael [@] gmail [dot] com
description: "Yet another blog on software stuff"
baseurl: ""
url: "https://agileek.github.io"
twitter_username: BitardMichael
github_username:  MichaelBitard

# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-redirect-from
  - jekyll-gist
